"""Builds the code to paste into Agentverse hosted agents.

    python build_hosted.py            # all three
    python build_hosted.py sprout     # or tutor / curriculum

- dist/sprout/: the agent students talk to, as a multi-file hosted agent. agent.py is the
  orchestrator; tutor_skill.py and curriculum_skill.py are the specialists' chat logic, run
  in-process; sprout_db.py, relay.py and routing.py are copied as they are. Create each file in
  the agent's editor (+ New File) with the same name.
- dist/tutor/agent.py and dist/curriculum/agent.py: the standalone specialist agents, one file
  each, for direct chats and for other orchestrators.

Hosted agents provide their identity through `agent = Agent()` and read secrets from the editor's
.env, so the local-only setup (seeds, ports, load_dotenv, the event loop line) is dropped.
No `from __future__ import annotations` anywhere: uAgents reads handler type hints as classes.
"""

import re
import sys
from pathlib import Path

HERE = Path(__file__).parent
DIST = HERE / "dist"
SHARED = ["sprout_db", "relay"]
PACKAGES = {
    "tutor": ["learning", "content", "cards", "game", "skill"],
    "curriculum": ["concept_map", "prompt", "cards", "skill"],
}


def strip_imports(src: str, modules) -> str:
    """Removes `from x import ...` lines (one-line or parenthesized) for the named modules."""
    names = "|".join(re.escape(m) for m in modules)
    return re.sub(rf"^from (?:{names}) import (?:\([^)]*\)|[^\n]*)\n", "", src, flags=re.M)


def body(path: Path) -> str:
    """A module's source without its docstring."""
    return re.sub(r'^""".*?"""\n', "", path.read_text(encoding="utf-8"), count=1, flags=re.S).lstrip("\n")


def bundle(package: str, inline_shared: bool) -> str:
    """One package's modules in dependency order, with their package-relative imports removed."""
    local = [rf"\.{m}" for m in PACKAGES[package]] + [rf"{package}\.{m}" for m in PACKAGES[package]]
    shared = SHARED if inline_shared else []
    parts = []
    for mod in shared:
        parts.append((mod, body(HERE / f"{mod}.py")))
    for mod in PACKAGES[package]:
        parts.append((f"{package}/{mod}", body(HERE / package / f"{mod}.py")))
    out = ""
    for name, src in parts:
        src = re.sub(rf"^from (?:{'|'.join(local)}) import (?:\([^)]*\)|[^\n]*)\n", "", src, flags=re.M)
        if inline_shared:
            src = strip_imports(src, SHARED)
        out += f"# ---- {name}.py ----\n{src.rstrip()}\n\n\n"
    return out


def hosted_wiring(src: str) -> str:
    """An agent.py's wiring, adapted for hosting: identity from Agentverse, no local setup."""
    src = re.sub(r'^""".*?"""\n', "", src, count=1, flags=re.S)
    src = re.sub(r"^from dotenv import load_dotenv\n\nload_dotenv\(\)[^\n]*\n", "", src, flags=re.M)
    src = re.sub(r"\n# Python 3\.14[^\n]*\nasyncio\.set_event_loop\(asyncio\.new_event_loop\(\)\)\n", "\n", src)
    src = re.sub(r"agent = Agent\(\n.*?\n\)\n", "agent = Agent()\n", src, flags=re.S)
    src = re.sub(r'\nif __name__ == "__main__":\n    agent\.run\(\)\n', "\n", src)
    src = src.replace("  # noqa: E402", "")
    return src.strip("\n") + "\n"


def header(title: str, needs: str) -> str:
    return (f'"""{title} (hosted build). Generated by uagents-python/build_hosted.py; edit the sources, not this.\n\n'
            f"{needs}\n"
            'No `from __future__ import annotations`: uAgents reads handler type hints as classes."""\n\n')


def build_specialist(package: str):
    wiring = hosted_wiring((HERE / package / "agent.py").read_text(encoding="utf-8"))
    wiring = strip_imports(wiring, SHARED + [f"{package}.{m}" for m in PACKAGES[package]])
    needs = "Needs ASI_ONE_API_KEY, SPACETIMEDB_TOKEN and SPACETIMEDB_DB in the editor's .env (plus TRUSTED_ORCHESTRATORS)."
    out = header(f"Sprout {package} agent", needs) + bundle(package, inline_shared=True) + "# ---- agent.py ----\n" + wiring
    write(DIST / package / "agent.py", out)


def build_sprout():
    folder = DIST / "sprout"
    for mod in SHARED:
        write(folder / f"{mod}.py", (HERE / f"{mod}.py").read_text(encoding="utf-8"))
    write(folder / "routing.py", (HERE / "orchestrator" / "routing.py").read_text(encoding="utf-8"))
    for package in PACKAGES:
        needs = f"The {package} chat logic, imported by agent.py and run in-process."
        write(folder / f"{package}_skill.py", header(f"Sprout {package} skill", needs) + bundle(package, inline_shared=False))
    wiring = hosted_wiring((HERE / "orchestrator" / "agent.py").read_text(encoding="utf-8"))
    wiring = wiring.replace("from orchestrator.routing import", "from routing import")
    for package in PACKAGES:
        wiring = wiring.replace(f"from {package}.skill import", f"from {package}_skill import")
    needs = ("Needs ASI_ONE_API_KEY, SPACETIMEDB_TOKEN and SPACETIMEDB_DB in the editor's .env, and the files\n"
             "sprout_db.py, relay.py, routing.py, tutor_skill.py and curriculum_skill.py next to it.")
    write(folder / "agent.py", header("Sprout orchestrator", needs) + wiring)


def write(path: Path, text: str):
    compile(text, str(path), "exec")  # a syntax error here would only show up after deploying
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    print(f"wrote {path.relative_to(HERE)} ({len(text.splitlines())} lines)")


if __name__ == "__main__":
    targets = sys.argv[1:] or ["sprout", "tutor", "curriculum"]
    for target in targets:
        build_sprout() if target == "sprout" else build_specialist(target)
