// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddConceptReducer from "../add_concept_reducer";
import AddPrerequisiteReducer from "../add_prerequisite_reducer";
import AdvanceGameReducer from "../advance_game_reducer";
import ArcadeAnswerReducer from "../arcade_answer_reducer";
import ClaimHostReducer from "../claim_host_reducer";
import ComputeNextStepReducer from "../compute_next_step_reducer";
import ConfirmCourseReducer from "../confirm_course_reducer";
import CreateCourseReducer from "../create_course_reducer";
import CreateGameReducer from "../create_game_reducer";
import EndGameReducer from "../end_game_reducer";
import EndSessionReducer from "../end_session_reducer";
import ForgetCourseReducer from "../forget_course_reducer";
import IngestConceptGraphReducer from "../ingest_concept_graph_reducer";
import JoinGameReducer from "../join_game_reducer";
import LeaveGameReducer from "../leave_game_reducer";
import RecordAttemptReducer from "../record_attempt_reducer";
import RegisterAgentReducer from "../register_agent_reducer";
import RemoveAgentReducer from "../remove_agent_reducer";
import RemoveConceptReducer from "../remove_concept_reducer";
import RemovePrerequisiteReducer from "../remove_prerequisite_reducer";
import SaveStudyCardReducer from "../save_study_card_reducer";
import SeedDemoReducer from "../seed_demo_reducer";
import SetConceptParamsReducer from "../set_concept_params_reducer";
import SetPreferredFormatReducer from "../set_preferred_format_reducer";
import SetStudyCardStatusReducer from "../set_study_card_status_reducer";
import StartSessionReducer from "../start_session_reducer";
import SubmitAnswerReducer from "../submit_answer_reducer";
import UpdateConceptReducer from "../update_concept_reducer";
import UpdateCourseReducer from "../update_course_reducer";
import UpsertLearnerReducer from "../upsert_learner_reducer";

export type AddConceptParams = __Infer<typeof AddConceptReducer>;
export type AddPrerequisiteParams = __Infer<typeof AddPrerequisiteReducer>;
export type AdvanceGameParams = __Infer<typeof AdvanceGameReducer>;
export type ArcadeAnswerParams = __Infer<typeof ArcadeAnswerReducer>;
export type ClaimHostParams = __Infer<typeof ClaimHostReducer>;
export type ComputeNextStepParams = __Infer<typeof ComputeNextStepReducer>;
export type ConfirmCourseParams = __Infer<typeof ConfirmCourseReducer>;
export type CreateCourseParams = __Infer<typeof CreateCourseReducer>;
export type CreateGameParams = __Infer<typeof CreateGameReducer>;
export type EndGameParams = __Infer<typeof EndGameReducer>;
export type EndSessionParams = __Infer<typeof EndSessionReducer>;
export type ForgetCourseParams = __Infer<typeof ForgetCourseReducer>;
export type IngestConceptGraphParams = __Infer<typeof IngestConceptGraphReducer>;
export type JoinGameParams = __Infer<typeof JoinGameReducer>;
export type LeaveGameParams = __Infer<typeof LeaveGameReducer>;
export type RecordAttemptParams = __Infer<typeof RecordAttemptReducer>;
export type RegisterAgentParams = __Infer<typeof RegisterAgentReducer>;
export type RemoveAgentParams = __Infer<typeof RemoveAgentReducer>;
export type RemoveConceptParams = __Infer<typeof RemoveConceptReducer>;
export type RemovePrerequisiteParams = __Infer<typeof RemovePrerequisiteReducer>;
export type SaveStudyCardParams = __Infer<typeof SaveStudyCardReducer>;
export type SeedDemoParams = __Infer<typeof SeedDemoReducer>;
export type SetConceptParamsParams = __Infer<typeof SetConceptParamsReducer>;
export type SetPreferredFormatParams = __Infer<typeof SetPreferredFormatReducer>;
export type SetStudyCardStatusParams = __Infer<typeof SetStudyCardStatusReducer>;
export type StartSessionParams = __Infer<typeof StartSessionReducer>;
export type SubmitAnswerParams = __Infer<typeof SubmitAnswerReducer>;
export type UpdateConceptParams = __Infer<typeof UpdateConceptReducer>;
export type UpdateCourseParams = __Infer<typeof UpdateCourseReducer>;
export type UpsertLearnerParams = __Infer<typeof UpsertLearnerReducer>;

