"""Bundle the curriculum agent into one file for an Agentverse hosted agent.

Hosted agents run a single agent.py with `agent = Agent()` provided identity,
so this inlines concept_map.py, prompt.py and cards.py and drops the local-only setup.
Run: python build_hosted.py  ->  dist/hosted_agent.py
"""

import re
from pathlib import Path

here = Path(__file__).parent


def body(name: str) -> str:
    src = (here / name).read_text()
    src = re.sub(r'^""".*?"""\n', "", src, count=1, flags=re.DOTALL)  # module docstring
    return src.replace("from __future__ import annotations\n", "")


agent = body("agent.py")
agent = re.sub(r"import spacetime_db\nfrom cards import .*\nfrom concept_map import .*\nfrom prompt import .*\n", "", agent)
agent = re.sub(r"agent = Agent\(\n.*?\n\)\n", "agent = Agent()\n", agent, flags=re.DOTALL)
agent = agent.replace('\nif __name__ == "__main__":\n    agent.run()\n', "")
agent = agent.replace("from dotenv import load_dotenv\n", "")
agent = re.sub(r"load_dotenv\(\)\n\n# Python 3.14.*?\nasyncio.set_event_loop\(asyncio.new_event_loop\(\)\)\n\n", "", agent, flags=re.DOTALL)

out = (
    '"""Sprout curriculum agent (hosted build). Generated by build_hosted.py; edit the source files, not this.\n\n'
    'Needs the agent secret ASI_ONE_API_KEY.\n'
    "No `from __future__ import annotations`: uAgents reads handler type hints as classes.\"\"\"\n\n"
    "# ---- concept_map.py ----\n" + body("concept_map.py")
    + "\n\n# ---- prompt.py ----\n" + body("prompt.py")
    + "\n\n# ---- cards.py ----\n" + body("cards.py")
    + "\n\n# ---- spacetime_db.py ----\n" + body("spacetime_db.py")
    + "\n\n# ---- agent.py ----\n" + agent
)
(here / "dist").mkdir(exist_ok=True)
(here / "dist" / "hosted_agent.py").write_text(out)
print(f"wrote dist/hosted_agent.py ({len(out.splitlines())} lines)")
