// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  GameQuestionInput,
} from "./types";

export default {
  hostAddress: __t.string(),
  courseId: __t.u64(),
  title: __t.string(),
  mode: __t.string(),
  template: __t.string(),
  secondsPerQuestion: __t.u32(),
  hostKey: __t.string(),
  get questions() {
    return __t.array(GameQuestionInput);
  },
};
