// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  gameId: __t.u64().name("game_id"),
  index: __t.u32(),
  conceptId: __t.u64().name("concept_id"),
  prompt: __t.string(),
  choices: __t.array(__t.string()),
  correctIndex: __t.option(__t.u32()).name("correct_index"),
  explanation: __t.option(__t.string()),
  choiceCounts: __t.array(__t.u32()).name("choice_counts"),
});
