// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  key: __t.string().primaryKey(),
  userAddress: __t.string().name("user_address"),
  courseId: __t.u64().name("course_id"),
  conceptId: __t.option(__t.u64()).name("concept_id"),
  format: __t.string(),
  mode: __t.string(),
  reason: __t.string(),
  computedAt: __t.timestamp().name("computed_at"),
});
