// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  userAddress: __t.string().name("user_address"),
  courseId: __t.option(__t.u64()).name("course_id"),
  startedAt: __t.timestamp().name("started_at"),
  endedAt: __t.option(__t.timestamp()).name("ended_at"),
  summary: __t.string(),
  lastConceptId: __t.option(__t.u64()).name("last_concept_id"),
});
