// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  userAddress: __t.string().name("user_address"),
  courseId: __t.u64().name("course_id"),
  conceptId: __t.u64().name("concept_id"),
  sessionId: __t.option(__t.u64()).name("session_id"),
  kind: __t.string(),
  format: __t.option(__t.string()),
  question: __t.option(__t.string()),
  correct: __t.bool(),
  pBefore: __t.f64().name("p_before"),
  pAfter: __t.f64().name("p_after"),
  createdAt: __t.timestamp().name("created_at"),
});
