// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  code: __t.string(),
  hostAddress: __t.string().name("host_address"),
  courseId: __t.u64().name("course_id"),
  title: __t.string(),
  mode: __t.string(),
  template: __t.string(),
  status: __t.string(),
  questionIndex: __t.u32().name("question_index"),
  questionCount: __t.u32().name("question_count"),
  secondsPerQuestion: __t.u32().name("seconds_per_question"),
  questionStartedAt: __t.option(__t.timestamp()).name("question_started_at"),
  hostIdentity: __t.option(__t.identity()).name("host_identity"),
  createdAt: __t.timestamp().name("created_at"),
  finishedAt: __t.option(__t.timestamp()).name("finished_at"),
});
