// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.10.2 (commit 58d2a40718c59535fd5c267e836d473298eb84d5).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AddConceptReducer from "./add_concept_reducer";
import AddPrerequisiteReducer from "./add_prerequisite_reducer";
import AdvanceGameReducer from "./advance_game_reducer";
import ClaimHostReducer from "./claim_host_reducer";
import ComputeNextStepReducer from "./compute_next_step_reducer";
import ConfirmCourseReducer from "./confirm_course_reducer";
import CreateCourseReducer from "./create_course_reducer";
import CreateGameReducer from "./create_game_reducer";
import EndGameReducer from "./end_game_reducer";
import EndSessionReducer from "./end_session_reducer";
import ForgetCourseReducer from "./forget_course_reducer";
import IngestConceptGraphReducer from "./ingest_concept_graph_reducer";
import JoinGameReducer from "./join_game_reducer";
import LeaveGameReducer from "./leave_game_reducer";
import RecordAttemptReducer from "./record_attempt_reducer";
import RegisterAgentReducer from "./register_agent_reducer";
import RemoveAgentReducer from "./remove_agent_reducer";
import RemoveConceptReducer from "./remove_concept_reducer";
import RemovePrerequisiteReducer from "./remove_prerequisite_reducer";
import SaveStudyCardReducer from "./save_study_card_reducer";
import SeedDemoReducer from "./seed_demo_reducer";
import SetConceptParamsReducer from "./set_concept_params_reducer";
import SetPreferredFormatReducer from "./set_preferred_format_reducer";
import SetStudyCardStatusReducer from "./set_study_card_status_reducer";
import StartSessionReducer from "./start_session_reducer";
import SubmitAnswerReducer from "./submit_answer_reducer";
import UpdateConceptReducer from "./update_concept_reducer";
import UpdateCourseReducer from "./update_course_reducer";
import UpsertLearnerReducer from "./upsert_learner_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import AttemptRow from "./attempt_table";
import ConceptRow from "./concept_table";
import CourseRow from "./course_table";
import FormatWeightRow from "./format_weight_table";
import GameRow from "./game_table";
import GameQuestionRow from "./game_question_table";
import LearnerRow from "./learner_table";
import MasteryRow from "./mastery_table";
import NextStepRow from "./next_step_table";
import PlayerRow from "./player_table";
import PlayerAnswerRow from "./player_answer_table";
import PrerequisiteRow from "./prerequisite_table";
import SessionRow from "./session_table";
import StudyCardRow from "./study_card_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  attempt: __table({
    name: 'attempt',
    indexes: [
      { accessor: 'conceptId', name: 'attempt_concept_id_idx_btree', algorithm: 'btree', columns: [
        'conceptId',
      ] },
      { accessor: 'courseId', name: 'attempt_course_id_idx_btree', algorithm: 'btree', columns: [
        'courseId',
      ] },
      { accessor: 'id', name: 'attempt_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'userAddress', name: 'attempt_user_address_idx_btree', algorithm: 'btree', columns: [
        'userAddress',
      ] },
    ],
    constraints: [
      { name: 'attempt_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AttemptRow),
  concept: __table({
    name: 'concept',
    indexes: [
      { accessor: 'courseId', name: 'concept_course_id_idx_btree', algorithm: 'btree', columns: [
        'courseId',
      ] },
      { accessor: 'id', name: 'concept_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'concept_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ConceptRow),
  course: __table({
    name: 'course',
    indexes: [
      { accessor: 'id', name: 'course_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'userAddress', name: 'course_user_address_idx_btree', algorithm: 'btree', columns: [
        'userAddress',
      ] },
    ],
    constraints: [
      { name: 'course_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CourseRow),
  formatWeight: __table({
    name: 'format_weight',
    indexes: [
      { accessor: 'key', name: 'format_weight_key_idx_btree', algorithm: 'btree', columns: [
        'key',
      ] },
      { accessor: 'userAddress', name: 'format_weight_user_address_idx_btree', algorithm: 'btree', columns: [
        'userAddress',
      ] },
    ],
    constraints: [
      { name: 'format_weight_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, FormatWeightRow),
  game: __table({
    name: 'game',
    indexes: [
      { accessor: 'code', name: 'game_code_idx_btree', algorithm: 'btree', columns: [
        'code',
      ] },
      { accessor: 'hostAddress', name: 'game_host_address_idx_btree', algorithm: 'btree', columns: [
        'hostAddress',
      ] },
      { accessor: 'id', name: 'game_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'game_code_key', constraint: 'unique', columns: ['code'] },
      { name: 'game_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, GameRow),
  gameQuestion: __table({
    name: 'game_question',
    indexes: [
      { accessor: 'gameId', name: 'game_question_game_id_idx_btree', algorithm: 'btree', columns: [
        'gameId',
      ] },
      { accessor: 'id', name: 'game_question_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'game_question_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, GameQuestionRow),
  learner: __table({
    name: 'learner',
    indexes: [
      { accessor: 'address', name: 'learner_address_idx_btree', algorithm: 'btree', columns: [
        'address',
      ] },
    ],
    constraints: [
      { name: 'learner_address_key', constraint: 'unique', columns: ['address'] },
    ],
  }, LearnerRow),
  mastery: __table({
    name: 'mastery',
    indexes: [
      { accessor: 'courseId', name: 'mastery_course_id_idx_btree', algorithm: 'btree', columns: [
        'courseId',
      ] },
      { accessor: 'key', name: 'mastery_key_idx_btree', algorithm: 'btree', columns: [
        'key',
      ] },
      { accessor: 'userAddress', name: 'mastery_user_address_idx_btree', algorithm: 'btree', columns: [
        'userAddress',
      ] },
    ],
    constraints: [
      { name: 'mastery_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, MasteryRow),
  nextStep: __table({
    name: 'next_step',
    indexes: [
      { accessor: 'key', name: 'next_step_key_idx_btree', algorithm: 'btree', columns: [
        'key',
      ] },
      { accessor: 'userAddress', name: 'next_step_user_address_idx_btree', algorithm: 'btree', columns: [
        'userAddress',
      ] },
    ],
    constraints: [
      { name: 'next_step_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, NextStepRow),
  player: __table({
    name: 'player',
    indexes: [
      { accessor: 'gameId', name: 'player_game_id_idx_btree', algorithm: 'btree', columns: [
        'gameId',
      ] },
      { accessor: 'id', name: 'player_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'identity', name: 'player_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PlayerRow),
  playerAnswer: __table({
    name: 'player_answer',
    indexes: [
      { accessor: 'gameId', name: 'player_answer_game_id_idx_btree', algorithm: 'btree', columns: [
        'gameId',
      ] },
      { accessor: 'id', name: 'player_answer_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'playerId', name: 'player_answer_player_id_idx_btree', algorithm: 'btree', columns: [
        'playerId',
      ] },
    ],
    constraints: [
      { name: 'player_answer_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PlayerAnswerRow),
  prerequisite: __table({
    name: 'prerequisite',
    indexes: [
      { accessor: 'conceptId', name: 'prerequisite_concept_id_idx_btree', algorithm: 'btree', columns: [
        'conceptId',
      ] },
      { accessor: 'courseId', name: 'prerequisite_course_id_idx_btree', algorithm: 'btree', columns: [
        'courseId',
      ] },
      { accessor: 'id', name: 'prerequisite_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'requiresId', name: 'prerequisite_requires_id_idx_btree', algorithm: 'btree', columns: [
        'requiresId',
      ] },
    ],
    constraints: [
      { name: 'prerequisite_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PrerequisiteRow),
  session: __table({
    name: 'session',
    indexes: [
      { accessor: 'id', name: 'session_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'userAddress', name: 'session_user_address_idx_btree', algorithm: 'btree', columns: [
        'userAddress',
      ] },
    ],
    constraints: [
      { name: 'session_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SessionRow),
  studyCard: __table({
    name: 'study_card',
    indexes: [
      { accessor: 'courseId', name: 'study_card_course_id_idx_btree', algorithm: 'btree', columns: [
        'courseId',
      ] },
      { accessor: 'id', name: 'study_card_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'userAddress', name: 'study_card_user_address_idx_btree', algorithm: 'btree', columns: [
        'userAddress',
      ] },
    ],
    constraints: [
      { name: 'study_card_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, StudyCardRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("add_concept", AddConceptReducer),
  __reducerSchema("add_prerequisite", AddPrerequisiteReducer),
  __reducerSchema("advance_game", AdvanceGameReducer),
  __reducerSchema("claim_host", ClaimHostReducer),
  __reducerSchema("compute_next_step", ComputeNextStepReducer),
  __reducerSchema("confirm_course", ConfirmCourseReducer),
  __reducerSchema("create_course", CreateCourseReducer),
  __reducerSchema("create_game", CreateGameReducer),
  __reducerSchema("end_game", EndGameReducer),
  __reducerSchema("end_session", EndSessionReducer),
  __reducerSchema("forget_course", ForgetCourseReducer),
  __reducerSchema("ingest_concept_graph", IngestConceptGraphReducer),
  __reducerSchema("join_game", JoinGameReducer),
  __reducerSchema("leave_game", LeaveGameReducer),
  __reducerSchema("record_attempt", RecordAttemptReducer),
  __reducerSchema("register_agent", RegisterAgentReducer),
  __reducerSchema("remove_agent", RemoveAgentReducer),
  __reducerSchema("remove_concept", RemoveConceptReducer),
  __reducerSchema("remove_prerequisite", RemovePrerequisiteReducer),
  __reducerSchema("save_study_card", SaveStudyCardReducer),
  __reducerSchema("seed_demo", SeedDemoReducer),
  __reducerSchema("set_concept_params", SetConceptParamsReducer),
  __reducerSchema("set_preferred_format", SetPreferredFormatReducer),
  __reducerSchema("set_study_card_status", SetStudyCardStatusReducer),
  __reducerSchema("start_session", StartSessionReducer),
  __reducerSchema("submit_answer", SubmitAnswerReducer),
  __reducerSchema("update_concept", UpdateConceptReducer),
  __reducerSchema("update_course", UpdateCourseReducer),
  __reducerSchema("upsert_learner", UpsertLearnerReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.10.2" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

