// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  address: __t.string().primaryKey(),
  displayName: __t.option(__t.string()).name("display_name"),
  plan: __t.string(),
  preferredFormat: __t.option(__t.string()).name("preferred_format"),
  createdAt: __t.timestamp().name("created_at"),
  lastActiveAt: __t.timestamp().name("last_active_at"),
});
