// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  key: __t.string().primaryKey(),
  userAddress: __t.string().name("user_address"),
  courseId: __t.u64().name("course_id"),
  conceptId: __t.u64().name("concept_id"),
  pMastered: __t.f64().name("p_mastered"),
  attempts: __t.u32(),
  correct: __t.u32(),
  lastSeen: __t.option(__t.timestamp()).name("last_seen"),
  nextReview: __t.option(__t.timestamp()).name("next_review"),
  ease: __t.f64(),
  intervalDays: __t.f64().name("interval_days"),
  repetitions: __t.u32(),
});
