// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  address: __t.string(),
  conceptId: __t.u64(),
  pInit: __t.option(__t.f64()),
  pLearn: __t.option(__t.f64()),
  pSlip: __t.option(__t.f64()),
  pGuess: __t.option(__t.f64()),
};
