// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Agent = __t.object("Agent", {
  identity: __t.identity(),
  name: __t.string(),
  registeredAt: __t.timestamp(),
});
export type Agent = __Infer<typeof Agent>;

export const Attempt = __t.object("Attempt", {
  id: __t.u64(),
  userAddress: __t.string(),
  courseId: __t.u64(),
  conceptId: __t.u64(),
  sessionId: __t.option(__t.u64()),
  kind: __t.string(),
  format: __t.option(__t.string()),
  question: __t.option(__t.string()),
  correct: __t.bool(),
  pBefore: __t.f64(),
  pAfter: __t.f64(),
  createdAt: __t.timestamp(),
});
export type Attempt = __Infer<typeof Attempt>;

export const Concept = __t.object("Concept", {
  id: __t.u64(),
  courseId: __t.u64(),
  name: __t.string(),
  summary: __t.string(),
  embedding: __t.array(__t.f32()),
  pInit: __t.f64(),
  pLearn: __t.f64(),
  pSlip: __t.f64(),
  pGuess: __t.f64(),
});
export type Concept = __Infer<typeof Concept>;

export const ConceptInput = __t.object("ConceptInput", {
  name: __t.string(),
  summary: __t.string(),
  embedding: __t.array(__t.f32()),
  pInit: __t.option(__t.f64()),
});
export type ConceptInput = __Infer<typeof ConceptInput>;

export const Config = __t.object("Config", {
  id: __t.u8(),
  owner: __t.identity(),
});
export type Config = __Infer<typeof Config>;

export const Course = __t.object("Course", {
  id: __t.u64(),
  userAddress: __t.string(),
  name: __t.string(),
  currentUnit: __t.option(__t.string()),
  examDate: __t.option(__t.timestamp()),
  rawSyllabus: __t.string(),
  status: __t.string(),
  createdAt: __t.timestamp(),
});
export type Course = __Infer<typeof Course>;

export const EdgeInput = __t.object("EdgeInput", {
  concept: __t.string(),
  requires: __t.string(),
  confidence: __t.f64(),
});
export type EdgeInput = __Infer<typeof EdgeInput>;

export const FormatWeight = __t.object("FormatWeight", {
  key: __t.string(),
  userAddress: __t.string(),
  format: __t.string(),
  alpha: __t.f64(),
  beta: __t.f64(),
  uses: __t.u32(),
});
export type FormatWeight = __Infer<typeof FormatWeight>;

export const Game = __t.object("Game", {
  id: __t.u64(),
  code: __t.string(),
  hostAddress: __t.string(),
  courseId: __t.u64(),
  title: __t.string(),
  status: __t.string(),
  questionIndex: __t.u32(),
  questionCount: __t.u32(),
  secondsPerQuestion: __t.u32(),
  questionStartedAt: __t.option(__t.timestamp()),
  hostIdentity: __t.option(__t.identity()),
  createdAt: __t.timestamp(),
  finishedAt: __t.option(__t.timestamp()),
});
export type Game = __Infer<typeof Game>;

export const GameChoice = __t.object("GameChoice", {
  answerId: __t.u64(),
  choice: __t.u32(),
});
export type GameChoice = __Infer<typeof GameChoice>;

export const GameQuestion = __t.object("GameQuestion", {
  id: __t.u64(),
  gameId: __t.u64(),
  index: __t.u32(),
  conceptId: __t.u64(),
  prompt: __t.string(),
  choices: __t.array(__t.string()),
  correctIndex: __t.option(__t.u32()),
  explanation: __t.option(__t.string()),
  choiceCounts: __t.array(__t.u32()),
});
export type GameQuestion = __Infer<typeof GameQuestion>;

export const GameQuestionInput = __t.object("GameQuestionInput", {
  conceptId: __t.u64(),
  prompt: __t.string(),
  choices: __t.array(__t.string()),
  answer: __t.u32(),
  explanation: __t.string(),
});
export type GameQuestionInput = __Infer<typeof GameQuestionInput>;

export const GameSecret = __t.object("GameSecret", {
  gameId: __t.u64(),
  hostKey: __t.string(),
  answers: __t.array(__t.u32()),
  explanations: __t.array(__t.string()),
});
export type GameSecret = __Infer<typeof GameSecret>;

export const GameTimer = __t.object("GameTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  gameId: __t.u64(),
  questionIndex: __t.u32(),
});
export type GameTimer = __Infer<typeof GameTimer>;

export const Learner = __t.object("Learner", {
  address: __t.string(),
  displayName: __t.option(__t.string()),
  preferredFormat: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  lastActiveAt: __t.timestamp(),
});
export type Learner = __Infer<typeof Learner>;

export const Mastery = __t.object("Mastery", {
  key: __t.string(),
  userAddress: __t.string(),
  courseId: __t.u64(),
  conceptId: __t.u64(),
  pMastered: __t.f64(),
  attempts: __t.u32(),
  correct: __t.u32(),
  lastSeen: __t.option(__t.timestamp()),
  nextReview: __t.option(__t.timestamp()),
  ease: __t.f64(),
  intervalDays: __t.f64(),
  repetitions: __t.u32(),
});
export type Mastery = __Infer<typeof Mastery>;

export const NextStep = __t.object("NextStep", {
  key: __t.string(),
  userAddress: __t.string(),
  courseId: __t.u64(),
  conceptId: __t.option(__t.u64()),
  format: __t.string(),
  mode: __t.string(),
  reason: __t.string(),
  computedAt: __t.timestamp(),
});
export type NextStep = __Infer<typeof NextStep>;

export const Player = __t.object("Player", {
  id: __t.u64(),
  gameId: __t.u64(),
  identity: __t.identity(),
  name: __t.string(),
  score: __t.u32(),
  streak: __t.u32(),
  correctCount: __t.u32(),
  learnerAddress: __t.option(__t.string()),
  joinedAt: __t.timestamp(),
});
export type Player = __Infer<typeof Player>;

export const PlayerAnswer = __t.object("PlayerAnswer", {
  id: __t.u64(),
  gameId: __t.u64(),
  playerId: __t.u64(),
  questionIndex: __t.u32(),
  answeredMs: __t.u32(),
  correct: __t.option(__t.bool()),
  points: __t.u32(),
});
export type PlayerAnswer = __Infer<typeof PlayerAnswer>;

export const Prerequisite = __t.object("Prerequisite", {
  id: __t.u64(),
  courseId: __t.u64(),
  conceptId: __t.u64(),
  requiresId: __t.u64(),
  confidence: __t.f64(),
});
export type Prerequisite = __Infer<typeof Prerequisite>;

export const Session = __t.object("Session", {
  id: __t.u64(),
  userAddress: __t.string(),
  courseId: __t.option(__t.u64()),
  startedAt: __t.timestamp(),
  endedAt: __t.option(__t.timestamp()),
  summary: __t.string(),
  lastConceptId: __t.option(__t.u64()),
});
export type Session = __Infer<typeof Session>;

export const StudyCard = __t.object("StudyCard", {
  id: __t.u64(),
  userAddress: __t.string(),
  courseId: __t.u64(),
  conceptId: __t.option(__t.u64()),
  kind: __t.string(),
  payloadJson: __t.string(),
  status: __t.string(),
  createdAt: __t.timestamp(),
});
export type StudyCard = __Infer<typeof StudyCard>;

