"""Bundle the tutor agent into one file for an Agentverse hosted agent.

Hosted agents run a single agent.py with `agent = Agent()` provided identity,
so this inlines ../sprout_db.py and the local modules and drops the local-only setup.
Run: python build_hosted.py  ->  dist/hosted_agent.py
"""

import re
from pathlib import Path

here = Path(__file__).parent
MODULES = ["sprout_db", "relay", "learning", "content", "cards"]
LOCAL_IMPORT = re.compile(rf"^from ({'|'.join(MODULES)}) import \(?[^)]*?\)?\n(?=\S|\n)", re.M)


def body(name: str) -> str:
    path = here / f"{name}.py" if (here / f"{name}.py").exists() else here.parent / f"{name}.py"
    src = path.read_text()
    src = re.sub(r'^""".*?"""\n', "", src, count=1, flags=re.DOTALL)  # module docstring
    return LOCAL_IMPORT.sub("", src)


agent = body("agent")
agent = re.sub(r"sys\.path\.insert\(.*\n\n", "", agent)
agent = re.sub(r"agent = Agent\(\n.*?\n\)\n", "agent = Agent()\n", agent, flags=re.DOTALL)
agent = agent.replace('\nif __name__ == "__main__":\n    agent.run()\n', "")
agent = agent.replace("from dotenv import load_dotenv\n", "")
agent = re.sub(r"load_dotenv\(\)\n\n# Python 3.14.*?\nasyncio.set_event_loop\(asyncio.new_event_loop\(\)\)\n\n", "", agent, flags=re.DOTALL)

out = (
    '"""Sprout tutor agent (hosted build). Generated by build_hosted.py; edit the source files, not this.\n\n'
    "Needs ASI_ONE_API_KEY and SPACETIMEDB_TOKEN (plus SPACETIMEDB_DB) in the editor's .env.\n"
    "No `from __future__ import annotations`: uAgents reads handler type hints as classes.\"\"\"\n\n"
    + "".join(f"# ---- {m}.py ----\n{body(m)}\n\n" for m in MODULES)
    + "# ---- agent.py ----\n" + agent
)
(here / "dist").mkdir(exist_ok=True)
(here / "dist" / "hosted_agent.py").write_text(out)
print(f"wrote dist/hosted_agent.py ({len(out.splitlines())} lines)")
